### ISSUE TITLE
A question about the evaluation metric

### ISSUE THREAD

**Issue by liuyuan-pal** [zjhthu/OANet#15]
Hi,
I have a minor question about the evaluation metrics. In the paper, the standard metric is mAP under 5 degree. But I find that the computation of mAP uses an interval of 5 degree (https://github.com/zjhthu/OANet/blob/51d71ff3f57161e912ec72420cd91cf7db64ab74/core/test.py#L47), so that the actual metric is the precision of pose under 5 degree. I don't know whether I have missed any part of this code. 

Thank you!

**Comment by zjhthu** [comment]
Yes, as done in [PointCN](https://github.com/vcg-uvic/learned-correspondence-release/blob/master/tests.py#L316), we use approximate mAP as the metric. We choose mAP@5° as the default metric because a strict metric is more useful in 3D reconstruction tasks. In our implementation, mAP@5° is happened to be equal to the precision@5°.

We also notice that there are some [works](https://github.com/magicleap/SuperGluePretrainedNetwork) report exact AUC, which is also ok.

**Comment by liuyuan-pal** [comment]
Thanks for the answer.
